"use client"

import { GraduationCap, Plus, Sparkles, ArrowRight, BookOpen, Target } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { useState, useEffect } from 'react'
import { useAuth } from '@/lib/user-context'
import { useRouter } from 'next/navigation'

interface SavedQuery {
  id: string
  query_text: string
  created_at: string
}

export default function LearningPathPage() {
  const { user, authLoading } = useAuth()
  const router = useRouter()
  const [savedQueries, setSavedQueries] = useState<SavedQuery[]>([])
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [learningPath, setLearningPath] = useState<any>(null)

  const fetchSavedQueries = async () => {
    if (!user?.id) return
    try {
      const { createBrowserSupabaseClient } = await import('@/lib/supabase-client')
      const supabase = createBrowserSupabaseClient()
      const { data } = await supabase
        .from('user_saved_queries')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false })
      setSavedQueries(data || [])
    } catch (error) {
      console.error('Error fetching saved queries:', error)
    } finally {
      setLoading(false)
    }
  }

  const generateLearningPath = async () => {
    if (!user?.id) return
    setGenerating(true)
    try {
      const response = await fetch('/api/learning/generate-path', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userId: user.id }),
      })
      const data = await response.json()
      setLearningPath(data.path)
    } catch (error) {
      console.error('Error generating path:', error)
      alert('Failed to generate learning path. Please try again.')
    } finally {
      setGenerating(false)
    }
  }

  useEffect(() => {
    if (!authLoading && user) {
      fetchSavedQueries()
    } else if (!authLoading && !user) {
      router.push('/auth/login')
    }
  }, [user, authLoading])

  if (loading) {
    return (
      <div className="min-h-screen bg-white dark:bg-gray-900 flex items-center justify-center">
        <div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full"></div>
      </div>
    )
  }

  const hasData = savedQueries.length > 0 || learningPath

  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950">
      {/* Content page standard (aligned with discover design language): max-w-5xl for better use of space after sidebar */}
      <div className="max-w-5xl mx-auto px-4 md:px-8 py-8">
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-4xl font-bold flex items-center gap-3">
                <GraduationCap className="h-9 w-9" />
                Your Learning Path
              </h1>
              <p className="text-muted-foreground mt-2">AI-powered career-aligned learning roadmap</p>
            </div>
            {hasData && (
              <Button onClick={generateLearningPath} disabled={generating}>
                <Sparkles className="h-4 w-4 mr-2" />
                {generating ? 'Generating...' : 'Refresh with Grok'}
              </Button>
            )}
          </div>

          {!hasData ? (
            <Card className="max-w-2xl mx-auto text-center py-16">
              <CardContent>
                <Target className="h-16 w-16 mx-auto text-muted-foreground mb-6" />
                <CardTitle className="text-2xl mb-3">No learning path yet</CardTitle>
                <CardDescription className="text-base mb-8 max-w-sm mx-auto">
                  Your personalized learning path is built from the content you explore and save. 
                  Start discovering topics to unlock a full AI-generated career roadmap.
                </CardDescription>
                <Button size="lg" onClick={() => router.push('/discover')}>
                  Start Exploring
                  <ArrowRight className="ml-3 h-5 w-5" />
                </Button>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-8">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <BookOpen className="h-5 w-5" />
                    Your Career-Aligned Path
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  {learningPath ? (
                    <div className="space-y-6">
                      <p className="text-sm">Path generated by Grok based on your saved interests and queries.</p>
                    </div>
                  ) : (
                    <p className="text-muted-foreground">Your saved queries are ready. Click "Refresh with Grok" to generate your full learning path.</p>
                  )}
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>Saved Queries &amp; Interests</CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-3">
                    {savedQueries.map((query) => (
                      <li key={query.id} className="flex items-center gap-3 p-4 bg-muted rounded-2xl">
                        <span className="text-sm flex-1">{query.query_text}</span>
                        <span className="text-xs text-muted-foreground">
                          {new Date(query.created_at).toLocaleDateString()}
                        </span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            </div>
          )}
      </div>
    </div>
  )
}
