// lib/progress.ts
// Progress tracking utilities
import { useCallback } from 'react'
import { createBrowserSupabaseClient } from './supabase-client'
import { useUser } from './user-context'
import { useOfflineQueue } from './offline-queue'
import type { ContentItem } from './data'

// Client-side helper functions
async function getUserProgressForContent(userId: string, contentId: string) {
  const supabase = createBrowserSupabaseClient()
  const { data, error } = await supabase
    .from('user_progress')
    .select('*')
    .eq('user_id', userId)
    .eq('content_id', contentId)
    .single()

  if (error && error.code !== 'PGRST116') { // PGRST116 is "not found"
    console.warn('Database not available for user progress, using fallback data:', error.message)
    return null
  }

  return data
}

async function ensureContentItemExists(contentId: string): Promise<void> {
  const supabase = createBrowserSupabaseClient()

  // Check if content already exists
  const { data: existing } = await supabase
    .from('content_items')
    .select('id')
    .eq('id', contentId)
    .single()

  if (existing) return

  // Create lightweight placeholder for dynamic/AI-generated content (e.g. grok- feed cards)
  // This satisfies the FK constraint without requiring schema changes or full content duplication
  const placeholderTitle = contentId.startsWith('grok-')
    ? `AI Lesson • ${contentId.split('-').slice(1, 3).join(' ')}`
    : `Dynamic Content • ${contentId}`

  const { error: insertError } = await supabase
    .from('content_items')
    .insert({
      id: contentId,
      title: placeholderTitle,
      content: 'This lesson was dynamically generated by AI for your personalized feed. Full interactive content is available in the learning interface.',
      type: 'text',
      difficulty: 'beginner',
      tags: contentId.startsWith('grok-') ? ['ai-generated', 'dynamic-feed'] : ['dynamic'],
      read_time: 5,
      is_published: true,
      likes: 0,
      views: 0,
      is_featured: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
      // category_id left null (optional in schema) — safe for placeholders
    })

  if (insertError) {
    console.warn('Could not create placeholder content item for progress tracking:', insertError.message)
    // Do not throw — let original progress insert fail gracefully if this fails
  }
}

async function updateUserProgress(userId: string, contentId: string, updates: any) {
  const supabase = createBrowserSupabaseClient()

  // Ensure content exists (handles dynamic grok- feed cards and any future dynamic content)
  await ensureContentItemExists(contentId)

  // First check if progress exists
  const existing = await getUserProgressForContent(userId, contentId)

  if (existing) {
    // Update existing progress
    const { data, error } = await supabase
      .from('user_progress')
      .update({
        ...updates,
        last_accessed_at: new Date().toISOString(),
        completed_at: updates.status === 'completed' ? new Date().toISOString() : existing.completed_at
      })
      .eq('user_id', userId)
      .eq('content_id', contentId)
      .select()
      .single()

    if (error) {
      console.warn('Database not available for progress update, using fallback:', error.message)
      return null
    }

    return data
  } else {
    // Create new progress
    const { data, error } = await supabase
      .from('user_progress')
      .insert({
        user_id: userId,
        content_id: contentId,
        status: updates.status || 'in_progress',
        progress_percentage: updates.progress_percentage || 0,
        time_spent: updates.time_spent || 0,
        last_accessed_at: new Date().toISOString(),
        completed_at: updates.status === 'completed' ? new Date().toISOString() : null
      })
      .select()
      .single()

    if (error) {
      console.warn('Database not available for progress creation, using fallback:', error.message)
      return null
    }

    return data
  }
}

async function getUserProgress(userId: string) {
  const supabase = createBrowserSupabaseClient()
  const { data, error } = await supabase
    .from('user_progress')
    .select(`
      *,
      content:content_items(*, category:categories(*))
    `)
    .eq('user_id', userId)
    .order('last_accessed_at', { ascending: false })

  if (error) {
    console.warn('Database not available for user progress, using fallback data:', error.message)
    return []
  }

  return data || []
}

/**
 * Single source of truth for progress-aware feeds.
 * Import this in any feed component (including test/quiz cards) to automatically
 * exclude content the user has already completed.
 */
export async function getRecommendedFeedContent(userId: string, limit = 10): Promise<ContentItem[]> {
  const supabase = createBrowserSupabaseClient()

  try {
    // Get progress rows and treat both status=completed OR progress_percentage=100 as completed
    const { data: progressData } = await supabase
      .from('user_progress')
      .select('content_id, status, progress_percentage')
      .eq('user_id', userId)

    const completedIds = (progressData || [])
      .filter((p: any) => p.status === 'completed' || p.progress_percentage === 100)
      .map((p: any) => p.content_id)

    let query = supabase
      .from('content_items')
      .select(`*, category:categories(*)`)
      .eq('is_published', true)

    if (completedIds.length > 0) {
      // Correct Supabase syntax — pass array directly
      query = query.not('id', 'in', completedIds)
    }

    const { data, error } = await query
      .order('created_at', { ascending: false })
      .limit(limit)

    if (error) {
      console.warn('getRecommendedFeedContent query failed, using fallback:', error.message)
      return []
    }

    return (data || []) as ContentItem[]
  } catch (err) {
    console.warn('getRecommendedFeedContent error:', err)
    return []
  }
}

export interface ProgressUpdate {
  contentId: string
  status?: 'not_started' | 'in_progress' | 'completed'
  progressPercentage?: number
  timeSpent?: number
}

export interface ProgressResult {
  success: boolean
  error?: string
  progress?: {
    id: string
    user_id: string
    content_id: string
    status: 'not_started' | 'in_progress' | 'completed'
    progress_percentage: number
    time_spent: number
    completed_at: string | null
    last_accessed_at: string
    created_at: string
  } | null
}

// Client-side progress functions for interactive components
export const progressUtils = {
  async updateProgress(update: ProgressUpdate): Promise<ProgressResult> {
    try {
      const supabase = createBrowserSupabaseClient()

      // Get current user
      const { data: { user }, error: userError } = await supabase.auth.getUser()

      if (userError || !user) {
        return {
          success: false,
          error: 'User not authenticated'
        }
      }

      // Check if we're offline
      const isOnline = navigator.onLine

      if (!isOnline) {
        // Queue for offline sync
        try {
          const { getOfflineQueue } = await import('./offline-queue')
          const queue = getOfflineQueue()
          await queue.addToQueue(update, user.id)

          return {
            success: true,
            progress: null, // Will be synced when back online
            error: undefined
          }
        } catch (queueError) {
          console.error('Failed to queue offline progress:', queueError)
          return {
            success: false,
            error: 'Failed to queue progress for offline sync'
          }
        }
      }

      // Get existing progress
      const existingProgress = await getUserProgressForContent(user.id, update.contentId)

      // Calculate new progress
      const newProgress = {
        status: update.status || existingProgress?.status || 'in_progress',
        progress_percentage: update.progressPercentage ?? existingProgress?.progress_percentage ?? 0,
        time_spent: (existingProgress?.time_spent || 0) + (update.timeSpent || 0)
      }

      // Update progress
      const result = await updateUserProgress(user.id, update.contentId, newProgress)

      return {
        success: !!result,
        progress: result,
        error: result ? undefined : 'Failed to update progress'
      }
    } catch (error) {
      console.error('Progress update error:', error)
      return {
        success: false,
        error: 'An unexpected error occurred'
      }
    }
  },

  async markAsCompleted(contentId: string): Promise<ProgressResult> {
    return await this.updateProgress({
      contentId,
      status: 'completed',
      progressPercentage: 100
    })
  },

  async markAsStarted(contentId: string): Promise<ProgressResult> {
    return await this.updateProgress({
      contentId,
      status: 'in_progress',
      progressPercentage: 0
    })
  },

  async addTimeSpent(contentId: string, timeSpent: number): Promise<ProgressResult> {
    return await this.updateProgress({
      contentId,
      timeSpent
    })
  },

  async getProgress(contentId: string) {
    try {
      const supabase = createBrowserSupabaseClient()

      const { data: { user }, error: userError } = await supabase.auth.getUser()

      if (userError || !user) {
        return null
      }

      return await getUserProgressForContent(user.id, contentId)
    } catch (error) {
      console.error('Get progress error:', error)
      return null
    }
  },

  async getAllProgress() {
    try {
      const supabase = createBrowserSupabaseClient()

      const { data: { user }, error: userError } = await supabase.auth.getUser()

      if (userError || !user) {
        return []
      }

      return await getUserProgress(user.id)
    } catch (error) {
      console.error('Get all progress error:', error)
      return []
    }
  }
}

// Hook for React components to manage progress
export function useProgress() {
  const { user } = useUser()

  const updateProgress = useCallback(async (update: ProgressUpdate) => {
    if (!user) {
      return {
        success: false,
        error: 'User not authenticated'
      }
    }

    try {
      const supabase = createBrowserSupabaseClient()

      // Get existing progress
      const existingProgress = await getUserProgressForContent(user.id, update.contentId)

      // Calculate new progress
      const newProgress = {
        status: update.status || existingProgress?.status || 'in_progress',
        progress_percentage: update.progressPercentage ?? existingProgress?.progress_percentage ?? 0,
        time_spent: (existingProgress?.time_spent || 0) + (update.timeSpent || 0)
      }

      // Update progress
      const result = await updateUserProgress(user.id, update.contentId, newProgress)

      return {
        success: !!result,
        progress: result,
        error: result ? undefined : 'Failed to update progress'
      }
    } catch (error) {
      console.error('Progress update error:', error)
      return {
        success: false,
        error: 'An unexpected error occurred'
      }
    }
  }, [user])

  const markCompleted = useCallback(async (contentId: string) => {
    return await updateProgress({
      contentId,
      status: 'completed',
      progressPercentage: 100
    })
  }, [updateProgress])

  const markStarted = useCallback(async (contentId: string) => {
    return await updateProgress({
      contentId,
      status: 'in_progress',
      progressPercentage: 0
    })
  }, [updateProgress])

  const addTime = useCallback(async (contentId: string, timeSpent: number) => {
    return await updateProgress({
      contentId,
      timeSpent
    })
  }, [updateProgress])

  const getProgress = useCallback(async (contentId: string) => {
    if (!user) return null

    return await getUserProgressForContent(user.id, contentId)
  }, [user])

  const getAllProgress = useCallback(async () => {
    if (!user) return []

    return await getUserProgress(user.id)
  }, [user])

  return {
    updateProgress,
    markCompleted,
    markStarted,
    addTime,
    getProgress,
    getAllProgress
  }
}